### ISSUE TITLE
Using OpenML Java apiconnector in Matlab

### ISSUE THREAD

**Issue by DraXus** [openml/java#1]
I tried to use Java apiconnector in Matlab R2012a but got the following error:
```
Java exception occurred:
java.lang.NoSuchMethodError:
com.thoughtworks.xstream.io.xml.DomDriver.<init>(Ljava/lang/String;Lcom/thoughtworks/xstream/io/naming/NameCoder;)V
 at org.openml.apiconnector.xstream.XstreamXmlMapping.getInstance(XstreamXmlMapping.java:63)
 at org.openml.apiconnector.io.HttpConnector.doApiRequest(HttpConnector.java:30)
 at org.openml.apiconnector.io.ApiSessionHash.openmlAuthenticate(ApiSessionHash.java:162)
 at org.openml.apiconnector.io.ApiSessionHash.update(ApiSessionHash.java:84)
 at org.openml.apiconnector.io.ApiSessionHash.set(ApiSessionHash.java:71)
 at org.openml.apiconnector.io.OpenmlConnector.<init>(OpenmlConnector.java:89)
```

This problem occurs because an older version of xstream is loaded by Matlab in the static java class path and therefore it's not using the xstream library provided in the dynamic java class path. I've been googling and couldn't find any elegant solution. Apparently, the only workaround would be to replace the xstream.jar file in the "jarext" Matlab folder with the new version, but that could lead to internal Matlab problems.

So at the moment it's not possible to use the Java apiconnector in Matlab, but I would like to leave this comment here for future reference.

**Comment by joaquinvanschoren** [comment]
I remember we had a similar issue with RapidMiner. Jan, do you remember how
you solved that?

**Comment by janvanrijn** [comment]
I didn't solve that problem yet, as there was a second problem with
RapidMiner as well.

A solution would be to downgrade xstream version of the apiconnector,
but that isn't straightforward as we rely heavily on one of the new
features.


2015-02-20 0:57 GMT+13:00 Joaquin Vanschoren <notifications@github.com>:
